### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by forz13** [FormidableLabs/nodejs-dashboard#42] opened 2016-11-01 11:43 UTC
- **Node Version**: Node v6.9.1
- **Package version**: v0.1.1
- **Platform**: SMP Debian 3.2.81-1 x86_64 GNU/Linux
When I required this package, the memory began to grow slowly
`const dashboard = require("nodejs-dashboard");`
**Memory schedule**
![deepinscreenshot-5958](https://cloud.githubusercontent.com/assets/8948915/19888612/281512fc-a049-11e6-9ea3-52613341c9c7.png)
**Comparison of 2 heap shapshots**
![0740fd1b21](https://cloud.githubusercontent.com/assets/8948915/19888628/4e85a956-a049-11e6-9153-94459267bf9d.jpg)

**Comment by jasonwilson** [comment] 2016-11-01 16:51
Thanks for filing this issue @forz13. Can you provide a little more detail? From the graph above it appears that memory is decreasing over time. Each telemetry event will create a new string to hold the data. I might be able to optimize this by writing to a reusable buffer instead.

**Comment by forz13** [comment] 2016-11-02 06:11
Yes, the amount of free memory decreases slowly over time, and I agree with you about the use of buffers in place of strings

**Comment by jasonwilson** [comment] 2016-11-02 13:14
To clarify is this 1) overall system memory or 2) utilization by a specific process, say: node or dashboard?

**Comment by forz13** [comment] 2016-11-03 07:11
1 - It's available RAM at OS.  I have't  now memory schedule for node process, but I am sure that the RAM is reduced due  increasing memory usage by node process

**Comment by steveslayden** [comment] 2016-11-04 21:09
@forz13, do you know about how much data is going out to stdout or stderr? It would have to be almost 2k/sec to be the sole issue here (looks like about a 200mb drop in 27hrs). Currently, the app is buffering all the stdout and stderr so they can be viewed in the windows. We probably need to cap this.

**Comment by jasonwilson** [comment] 2016-12-01 20:10
@forz13 can you try rerunning with `0.2.1`? We published some changes that should address these issues.

**Comment by forz13** [comment] 2016-12-01 20:31
@jasonwilson thank you, i will try it and give the graphics in the next few days

**Comment by jasonwilson** [comment] 2016-12-01 22:22
Closing for now. Feel free to reopen if the issue isn't resolved.

**Closed by jasonwilson** 2016-12-01 22:22 UTC
