### ISSUE TITLE
process.stdout.write no output

### ISSUE THREAD

**Issue by loretoparisi** [FormidableLabs/nodejs-dashboard#38] opened 2016-10-18 16:00 UTC
I have no output in the `stdout` view, when doing

``` javascript
const spinner = [ '⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏' ];
process.stdout.write(" "+spinner[ (index+1)% spinner.length ]+"\r" );
```

**Comment by jasonwilson** [comment] 2016-10-20 03:05
When trying a similar example it's printing each character on a separate line. This is because the dashboard is treating each stream event as a new log entry. Are the characters not visible to you? Does it work without the dashboard?

**Comment by loretoparisi** [comment] 2016-10-20 07:48
@jasonwilson running node from shell, it will print out the char and feed back to line start).

**Comment by aisapatino** [comment] 2017-02-14 18:16
Unable to reproduce. WIth the first example

```js
const spinner = [ '⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏' ];
process.stdout.write(" "+spinner[ (index+1)% spinner.length ]+"\r" );
```

I see nothing in stdout because it throws an error (`index is not defined`)

Second example

```js
const spinner = [ '⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏' ];
for(var count=0;count<100000;count++) process.stdout.write(" "+spinner[  (count+1)% spinner.length ]+"\033[0G" );
```

I see something like this

<img width="943" alt="screen shot 2017-02-14 at 10 12 46 am" src="https://cloud.githubusercontent.com/assets/1279315/22942379/2a4d2f12-f29e-11e6-920c-534490d4fb0c.png">

my terminal doesn't recognize `\033[0G` but there's definitely text going to stdout

**Comment by jjasonclark** [comment] 2017-11-29 02:23
Closing this issue as it seems to be caused by code error. If this is not the case please comment.

**Closed by jjasonclark** 2017-11-29 02:23 UTC
