### ISSUE TITLE
Please make compatible with Chalk so colors are brought across

### ISSUE THREAD

**Issue by craftfortress** [FormidableLabs/nodejs-dashboard#27] opened 2016-10-14 18:57 UTC
I love your module, however before my console logs were colored, as I am using Chalk.  It is really important as it helps make the output clearer. 

Please enable compatibility. 

Thank you and keep it up!

**Comment by jasonwilson** [comment] 2016-10-14 19:05
Duplicate of #15, until we find out a generalized solution you can try using the `FORCE_COLOR` flag with chalk.

**Closed** 2016-11-14 13:19 UTC
Labels: duplicate
